# Generated by Django 5.2.4 on 2025-07-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='第幾章')),
                ('verse', models.IntegerField(verbose_name='第幾節')),
                ('content', models.TextField(verbose_name='內容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptures.book', verbose_name='書名')),
            ],
            options={
                'ordering': ['book', 'chapter', 'verse'],
            },
        ),
    ]
