# Generated by Django 5.2.4 on 2025-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0002_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter',
            field=models.IntegerField(default=0, verbose_name='總共幾章'),
        ),
    ]
